version: '1'
services:
  popup:
    build:
      context: ./widget
      dockerfile: Dockerfile
    container_name: streampay-onramp-popup
    ports:
      - "7000:3000"
    depends_on:
      - db
      - backend
  platform:
    build:
      context: ./platform
      dockerfile: Dockerfile
    container_name: streampay-onramp-popup
    ports:
      - "7000:3000"
    depends_on:
      - db
      - backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: streampay-onramp-api
    ports:
      - "7010:3000"
    environment:
      DB_HOST: localhost
      DB_PORT: 7306
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
      DB_NAME: mydb
      JWT_SECRET: 
      APP_HOST: localhost:7010
      ZEPTOMAIL_TOKEN: 
      MASTER_ADDRESS:
      MASTER_KEY: 
  db:
    image: mysql:5.7
    container_name: streampay-onramp-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "7306:3306"

